// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-WHQaUffBtvlWnOOPgXBd-nOCK6F9y0',
    appId: '1:841335002556:android:5845a91ce2604cc4ed07b9',
    messagingSenderId: '841335002556',
    projectId: 'yo-project-b',
    storageBucket: 'yo-project-b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk7wkpYvi_wbhehzjzlUUpCgKYiSsyZg0',
    appId: '1:841335002556:ios:2739d5482706323aed07b9',
    messagingSenderId: '841335002556',
    projectId: 'yo-project-b',
    storageBucket: 'yo-project-b.appspot.com',
    iosClientId: '841335002556-pspgitl3grov25do3pgepp5gdq835l4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.a',
  );
}
